@login = http://localhost:3000/user/login
@singup = http://localhost:3000/user/usersp
@getData = http://localhost:3000/user/getData

POST {{login}}
Content-Type: application/json

{
    "dni" : "36",
    "password": "1234"
}

###
POST {{singup}}
Content-Type: application/json

{
    "nombre": "Juan",
    "dni" : "36",
    "correo": "co",
    "password" : "1234"
}

###
get {{getData}}
mani : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzNiIsImlhdCI6MTcxNjkwNDU2MSwiZXhwIjoxNzE2OTA0NjIxfQ.TF0-QftiH09njz_3UDKNMa5mdGyAoSt3jUE4fOS9Cx0



